import Head from 'next/head'
import Navbar from './components/Navbar'

export default function MainLayout ({ title, children }) {
  return (
    <>
      <Head>
        <title> {title} | TikTok</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='container'>
        <section className='section home_section'>
          {children}
        </section>
        <Navbar />
      </div>
    </>
  )
}
